<?php

declare(strict_types=1);

/**
 * -------------------------------------------------------------------------
 * NexusCore
 * -------------------------------------------------------------------------
 * File        : ReportService.php
 * Location    : app/Services/
 * Description : Reporting Engine — foundation service for all competition
 *               reports generated by NexusCore EMS.
 *
 * Responsibilities
 * -------------------------------------------------------------------------
 * • Authorization: who may generate reports
 * • Report ID generation (RPT-REG-YYYY-NNNNN)
 * • Retrieve and structure competition participant data
 * • Compute summary statistics (total, status, gender, type, dept, year)
 * • Compute department sub-totals
 * • Support dual mode: Registration Sheet + Attendance Sheet
 * • Retrieve attendance data when Attendance Sheet mode is selected
 * • Provide filter options (departments, years, statuses)
 *
 * Future Report Types (reuse this service)
 * -------------------------------------------------------------------------
 * • Registration Report   ← implemented here
 * • Attendance Sheet      ← implemented here (dual mode)
 * • Evaluation Sheet
 * • Results Sheet
 * • Winner List
 * • Certificate Register
 *
 * NOTE
 * -------------------------------------------------------------------------
 * This class NEVER contains raw SQL.
 * SQL belongs only in Model classes.
 *
 * -------------------------------------------------------------------------
 */

namespace App\Services;

use App\Database\Database;
use App\Models\ApplicationModel;
use App\Models\AttendanceRecordModel;
use App\Models\CompetitionCoordinatorModel;
use App\Models\CompetitionModel;
use App\Models\DepartmentModel;
use PDO;

final class ReportService
{
    private ApplicationModel            $appModel;
    private CompetitionModel            $compModel;
    private AttendanceRecordModel       $attendanceModel;
    private CompetitionCoordinatorModel $coordinatorModel;
    private DepartmentModel             $deptModel;
    private PDO                         $db;

    public function __construct()
    {
        $this->appModel         = new ApplicationModel();
        $this->compModel        = new CompetitionModel();
        $this->attendanceModel  = new AttendanceRecordModel();
        $this->coordinatorModel = new CompetitionCoordinatorModel();
        $this->deptModel        = new DepartmentModel();
        $this->db               = Database::getConnection();
    }

    /**
     * Get report dataset for a Symposium Event (Master Event Architecture).
     *
     * @param int   $symposiumEventId
     * @param array $filters
     * @return array
     */
    public function getEventReportData(int $symposiumEventId, array $filters = []): array
    {
        $sympEventModel = new \App\Models\SymposiumEventModel();
        $event = $sympEventModel->findById($symposiumEventId);

        if (!$event) {
            return ['success' => false, 'message' => 'Scheduled event not found.'];
        }

        $appModel = new ApplicationModel();
        $attModel = new AttendanceRecordModel();

        $participants = $attModel->getParticipantsForEventAttendance($symposiumEventId, 0);
        $totalRegistered = count($participants);

        $rulesSnapshot = !empty($event['snapshot_rules']) ? json_decode($event['snapshot_rules'], true) : [];
        $evalSnapshot  = !empty($event['snapshot_evaluation']) ? json_decode($event['snapshot_evaluation'], true) : [];

        return [
            'success'      => true,
            'report_id'    => sprintf('RPT-EVT-%d-%05d', date('Y'), $symposiumEventId),
            'generated_at' => date('Y-m-d H:i:s'),
            'event'        => [
                'symposium_event_id' => $event['symposium_event_id'],
                'event_code'         => $event['event_code'],
                'event_name'         => $event['event_name'],
                'category'           => $event['category'],
                'participation_type' => $event['participation_type'],
                'master_version'     => $event['master_version_used'],
                'event_date'         => $event['event_date'],
                'start_time'         => $event['start_time'],
                'end_time'           => $event['end_time'],
                'venue_name'         => $event['venue_name'] ?? 'TBA',
                'coordinator_name'   => $event['coordinator_name'] ?? 'Unassigned',
                'rules'              => $rulesSnapshot,
                'evaluation'         => $evalSnapshot,
            ],
            'summary'      => [
                'total_registered' => $totalRegistered,
                'max_capacity'     => $event['max_participants'] ?? 'Unlimited',
            ],
            'participants' => $participants,
        ];
    }

    /**
     * -------------------------------------------------------------------------
     * Can the user generate a participant report?
     *
     * Allowed Roles:
     * • Admin          — full access
     * • Principal      — full access
     * • HOD            — full access (scoped by department in the controller)
     * • Staff Coordinator — access to assigned competitions
     * • Staff          — read-only access
     *
     * Students must NEVER access this.
     *
     * @param array $user
     * @return bool
     * -------------------------------------------------------------------------
     */
    public function canGenerateReport(array $user): bool
    {
        return in_array($user['role'] ?? '', [
            'Admin',
            'Principal',
            'HOD',
            'Staff Coordinator',
            'Staff',
        ], true);
    }

    // =========================================================================
    // REPORT ID GENERATION
    // =========================================================================

    /**
     * -------------------------------------------------------------------------
     * Generate a unique Report ID.
     *
     * Format: RPT-REG-YYYY-NNNNN
     * Example: RPT-REG-2026-00012
     *
     * Uses a simple sequence based on the current second + microseconds
     * to ensure uniqueness within a session. For high-volume use, a
     * dedicated report_log table can be added as a future enhancement.
     *
     * @return string
     * -------------------------------------------------------------------------
     */
    public function generateReportId(): string
    {
        $year    = date('Y');
        $counter = (int) (microtime(true) * 100) % 99999;

        return sprintf('RPT-REG-%s-%05d', $year, $counter);
    }

    // =========================================================================
    // FILTER OPTIONS
    // =========================================================================

    /**
     * -------------------------------------------------------------------------
     * Get available filter options for the report form.
     *
     * Returns departments and years that have actual registrations for
     * the given competition, so the filter form only shows relevant options.
     *
     * @param int $competitionId
     * @return array  ['departments' => [...], 'years' => [...]]
     * -------------------------------------------------------------------------
     */
    public function getFilterOptions(int $competitionId): array
    {
        $sql = "
            SELECT DISTINCT
                d.department_id,
                d.department_name,
                s.academic_year
            FROM applications a
            INNER JOIN students    s ON s.student_id    = a.student_id
            INNER JOIN departments d ON d.department_id = s.department_id
            WHERE a.competition_id = :competition_id
            ORDER BY s.academic_year ASC, d.department_name ASC
        ";

        $stmt = $this->db->prepare($sql);
        $stmt->bindValue(':competition_id', $competitionId, PDO::PARAM_INT);
        $stmt->execute();
        $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $departments = [];
        $years       = [];
        $deptSeen    = [];

        foreach ($rows as $row) {
            $deptId = (int) $row['department_id'];
            if (!isset($deptSeen[$deptId])) {
                $departments[] = [
                    'department_id'   => $deptId,
                    'department_name' => $row['department_name'],
                ];
                $deptSeen[$deptId] = true;
            }
            $year = (int) $row['academic_year'];
            if (!in_array($year, $years, true)) {
                $years[] = $year;
            }
        }

        return [
            'departments' => $departments,
            'years'       => $years,
        ];
    }

    // =========================================================================
    // CORE REPORT DATA
    // =========================================================================

    /**
     * -------------------------------------------------------------------------
     * Retrieve all data needed to render the Competition Participant Register.
     *
     * Returns a fully-structured array that the template can render directly:
     *
     * [
     *   'competition'  => array,        // Full competition + symposium data
     *   'coordinators' => array,        // Event coordinators
     *   'summary'      => array,        // Totals: status, gender, type, dept, year
     *   'grouped'      => array,        // [year => [dept => [applications]]]
     *   'dept_totals'  => array,        // [year_dept_key => [total, approved, ...]]
     *   'has_attendance' => bool,       // Whether attendance data is available
     *   'report_id'    => string,
     *   'generated_at' => string,
     *   'generated_by' => string,
     * ]
     *
     * @param int    $competitionId
     * @param array  $filters        Keys: department_id, academic_year,
     *                               application_status, application_type,
     *                               report_type (registration|attendance),
     *                               watermark, session_id
     * @param array  $user           Current user array
     *
     * @return array
     * -------------------------------------------------------------------------
     */
    public function getParticipantRegisterData(
        int   $competitionId,
        array $filters,
        array $user
    ): array {

        // ------------------------------------------------------------------
        // 1. Competition + Symposium info
        // ------------------------------------------------------------------
        $competition = $this->compModel->findById($competitionId);
        if (!$competition) {
            return ['error' => 'Competition not found.'];
        }

        // ------------------------------------------------------------------
        // 2. Lead Coordinator name
        // ------------------------------------------------------------------
        $coordinators  = $this->coordinatorModel->getCoordinators($competitionId);
        $leadCoordName = '—';
        foreach ($coordinators as $c) {
            if (($c['coordinator_type'] ?? '') === 'Staff Coordinator'
                || ($c['responsibility'] ?? '') === 'Coordinator') {
                $leadCoordName = $c['full_name'] ?? '—';
                break;
            }
        }
        if ($leadCoordName === '—' && !empty($coordinators)) {
            $leadCoordName = $coordinators[0]['full_name'] ?? '—';
        }

        // ------------------------------------------------------------------
        // 3. Fetch participant applications (one optimized JOIN query)
        // ------------------------------------------------------------------
        $applications = $this->appModel->getForReport($competitionId, $filters);

        // ------------------------------------------------------------------
        // 4. Fetch team members for all team applications (one batch query)
        // ------------------------------------------------------------------
        $teamMembers = $this->appModel->getTeamMembersForReport($competitionId);

        // ------------------------------------------------------------------
        // 5. Fetch attendance data if Attendance Sheet mode
        // ------------------------------------------------------------------
        $attendanceMap = [];
        $hasAttendance = false;
        $reportType    = $filters['report_type'] ?? 'registration';

        if ($reportType === 'attendance') {
            $sessionId     = (int) ($filters['session_id'] ?? 0);
            $attendanceRows = $this->getAttendanceForCompetition($competitionId, $sessionId);
            foreach ($attendanceRows as $row) {
                $attendanceMap[(int) $row['application_id']] = $row['attendance_status'];
            }
            $hasAttendance = !empty($attendanceRows);
        }

        // ------------------------------------------------------------------
        // 6. Merge team members into application rows
        //    Attach attendance status
        // ------------------------------------------------------------------
        $serial = 0;
        foreach ($applications as &$app) {
            $serial++;
            $app['serial']            = $serial;
            $appId                    = (int) $app['application_id'];
            $app['members']           = $teamMembers[$appId] ?? [];
            $app['attendance_status'] = $attendanceMap[$appId] ?? null;
        }
        unset($app);

        // ------------------------------------------------------------------
        // 7. Compute summary statistics
        // ------------------------------------------------------------------
        $summary = $this->computeSummary($applications);

        // ------------------------------------------------------------------
        // 8. Group by Year → Department and compute dept sub-totals
        // ------------------------------------------------------------------
        [$grouped, $deptTotals] = $this->groupAndTally($applications);

        // ------------------------------------------------------------------
        // 9. Report metadata
        // ------------------------------------------------------------------
        return [
            'competition'   => $competition,
            'coordinators'  => $coordinators,
            'lead_coord'    => $leadCoordName,
            'summary'       => $summary,
            'grouped'       => $grouped,
            'dept_totals'   => $deptTotals,
            'has_attendance' => $hasAttendance,
            'report_type'   => $reportType,
            'filters'       => $filters,
            'report_id'     => $this->generateReportId(),
            'generated_at'  => \App\Helpers\DateHelper::dateTime('now'),
            'generated_by'  => $user['full_name'] ?? 'NexusCore EMS',
            'print_date'    => \App\Helpers\DateHelper::date('now'),
        ];
    }

    // =========================================================================
    // PRIVATE HELPERS
    // =========================================================================

    /**
     * Compute summary statistics across all applications.
     *
     * @param array $applications
     * @return array
     */
    private function computeSummary(array $applications): array
    {
        $summary = [
            'total'      => 0,
            'approved'   => 0,
            'pending'    => 0,
            'rejected'   => 0,
            'cancelled'  => 0,
            'male'       => 0,
            'female'     => 0,
            'individual' => 0,
            'team'       => 0,
            'departments'=> [],
            'years'      => [],
        ];

        foreach ($applications as $app) {
            $summary['total']++;

            // Status counts
            $status = strtolower($app['application_status'] ?? '');
            match ($status) {
                'approved'  => $summary['approved']++,
                'pending'   => $summary['pending']++,
                'rejected'  => $summary['rejected']++,
                'cancelled' => $summary['cancelled']++,
                default     => null,
            };

            // Gender counts
            $gender = strtolower($app['student_gender'] ?? '');
            if ($gender === 'male')   $summary['male']++;
            if ($gender === 'female') $summary['female']++;

            // Type counts
            $type = $app['application_type'] ?? 'Individual';
            if ($type === 'Team') $summary['team']++;
            else $summary['individual']++;

            // Unique departments
            $dept = $app['student_department'] ?? '';
            if ($dept && !in_array($dept, $summary['departments'], true)) {
                $summary['departments'][] = $dept;
            }

            // Unique years
            $year = (int) ($app['student_year'] ?? 0);
            if ($year && !in_array($year, $summary['years'], true)) {
                $summary['years'][] = $year;
            }
        }

        sort($summary['years']);
        sort($summary['departments']);

        $summary['dept_count'] = count($summary['departments']);
        $summary['year_count'] = count($summary['years']);

        return $summary;
    }

    /**
     * Group applications by Year → Department and tally per-department totals.
     *
     * @param array $applications
     * @return array  [$grouped, $deptTotals]
     */
    private function groupAndTally(array $applications): array
    {
        $grouped    = [];
        $deptTotals = [];

        foreach ($applications as $app) {
            $year = (int) ($app['student_year'] ?? 0);
            $dept = $app['student_department'] ?? 'Unknown';
            $key  = $year . '||' . $dept;

            $grouped[$year][$dept][] = $app;

            // Dept sub-totals
            if (!isset($deptTotals[$key])) {
                $deptTotals[$key] = [
                    'total'     => 0,
                    'approved'  => 0,
                    'pending'   => 0,
                    'rejected'  => 0,
                    'cancelled' => 0,
                    'male'      => 0,
                    'female'    => 0,
                ];
            }
            $deptTotals[$key]['total']++;
            $status = strtolower($app['application_status'] ?? '');
            match ($status) {
                'approved'  => $deptTotals[$key]['approved']++,
                'pending'   => $deptTotals[$key]['pending']++,
                'rejected'  => $deptTotals[$key]['rejected']++,
                'cancelled' => $deptTotals[$key]['cancelled']++,
                default     => null,
            };

            $gender = strtoupper(substr((string)($app['student_gender'] ?? ''), 0, 1));
            if ($gender === 'M') {
                $deptTotals[$key]['male']++;
            } elseif ($gender === 'F') {
                $deptTotals[$key]['female']++;
            }
        }

        // Sort by year ascending, then dept ascending within each year
        ksort($grouped);
        foreach ($grouped as &$depts) {
            ksort($depts);
        }
        unset($depts);

        return [$grouped, $deptTotals];
    }

    /**
     * Fetch attendance records for a competition (all sessions or specific session).
     *
     * @param int $competitionId
     * @param int $sessionId  0 = latest session
     * @return array  Keyed by application_id
     */
    private function getAttendanceForCompetition(int $competitionId, int $sessionId = 0): array
    {
        if ($sessionId > 0) {
            $sql = "
                SELECT application_id, attendance_status
                FROM attendance_records
                WHERE competition_id = :competition_id
                  AND session_id     = :session_id
            ";
            $stmt = $this->db->prepare($sql);
            $stmt->execute([
                'competition_id' => $competitionId,
                'session_id'     => $sessionId,
            ]);
        } else {
            // Get the most recent session's attendance
            $sql = "
                SELECT ar.application_id, ar.attendance_status
                FROM attendance_records ar
                INNER JOIN (
                    SELECT application_id, MAX(marked_at) AS latest_mark
                    FROM attendance_records
                    WHERE competition_id = :competition_id
                    GROUP BY application_id
                ) latest ON latest.application_id = ar.application_id
                         AND latest.latest_mark   = ar.marked_at
                WHERE ar.competition_id = :competition_id2
            ";
            $stmt = $this->db->prepare($sql);
            $stmt->execute([
                'competition_id'  => $competitionId,
                'competition_id2' => $competitionId,
            ]);
        }

        return $stmt->fetchAll(PDO::FETCH_ASSOC);
    }

    /**
     * Ordinal label for a year number (1 → "Year I", 2 → "Year II", etc.)
     *
     * @param int $year
     * @return string
     */
    public static function yearLabel(int $year): string
    {
        return match ($year) {
            1 => 'Year I — First Year',
            2 => 'Year II — Second Year',
            3 => 'Year III — Third Year',
            4 => 'Year IV — Fourth Year',
            5 => 'Year V — Fifth Year',
            default => "Year {$year}",
        };
    }

    /**
     * Generate the Registration Report PDF using dompdf
     *
     * @param array $event
     * @param array $symposium
     * @param array $filters
     * @param array $applications
     * @param array $stats
     */
    public function generateRegistrationReportPdf(array $event, array $symposium, array $filters, array $applications, array $stats): void
    {
        $settingModel = new \App\Models\SystemSettingModel();
        $rawLogoPath = $settingModel->getValue('COLLEGE_LOGO');
        
        $logoBase64 = '';
        if (!empty($rawLogoPath)) {
            $fullPath = __DIR__ . '/../../public/' . ltrim(str_replace(['NexusCore/', 'public/'], '', $rawLogoPath), '/');
            if (file_exists($fullPath)) {
                $type = pathinfo($fullPath, PATHINFO_EXTENSION);
                $data = file_get_contents($fullPath);
                $logoBase64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
            }
        }

        $nexusLogoPath = __DIR__ . '/../../public/assets/images/logo/nexuscore-logo.png';
        $nexusLogoBase64 = '';
        if (file_exists($nexusLogoPath)) {
            $type = pathinfo($nexusLogoPath, PATHINFO_EXTENSION);
            $data = file_get_contents($nexusLogoPath);
            $nexusLogoBase64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
        }

        $html = "
        <html>
        <head>
            <meta charset='utf-8'>
            <style>
                body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; margin: 10px; }
                h1, h2, h3, h4 { margin: 0 0 5px 0; text-align: center; }
                table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                th, td { border: 1px solid #ccc; padding: 6px; text-align: left; }
                th { background-color: #f8f9fa; font-weight: bold; }
                .text-center { text-align: center; }
                .meta-table { border: none; margin-bottom: 20px; }
                .meta-table td, .meta-table th { border: none; padding: 2px 10px; }
                .stats-container { display: table; width: 100%; margin-bottom: 20px; text-align: center; }
                .stat-box { display: table-cell; border: 1px solid #ccc; padding: 10px; width: 25%; }
                .stat-title { font-weight: bold; font-size: 10px; color: #666; text-transform: uppercase; }
                .stat-val { font-size: 16px; font-weight: bold; margin-top: 5px; }
                .page-break { page-break-after: always; }
                .team-header { background-color: #e9ecef; font-weight: bold; }
            </style>
        </head>
        <body>
            <table class='meta-table'>
                <tr>
                    <td style='width: 20%; text-align: center; vertical-align: middle;'>
                        " . ($logoBase64 ? "<img src='{$logoBase64}' style='height: 105px; width: auto;'>" : "") . "
                    </td>
                    <td style='width: 60%; text-align: center; vertical-align: middle;'>
                        <h2 style='margin: 0; font-size: 18px;'>Government Arts and Science College, Veerapandi, Theni dt</h2>
                        <h3 style='margin: 5px 0 0 0; color: #444;'>{$symposium['title']}</h3>
                        <h4 style='color: #666;'>Registration Report — {$event['event_name']}</h4>
                    </td>
                    <td style='width: 20%; text-align: center; vertical-align: middle;'>
                        " . ($nexusLogoBase64 ? "<img src='{$nexusLogoBase64}' style='height: 105px; width: auto;'><br>" : "") . "
                        <div style='font-size: 9px; margin-top: 5px; color: #777;'>Generated: " . date('Y-m-d H:i') . "</div>
                    </td>
                </tr>
            </table>
            
            <hr style='border-top: 1px solid #000; margin-bottom: 15px;'>

            <div class='stats-container'>
                <div class='stat-box'>
                    <div class='stat-title'>Total Students Applied</div>
                    <div class='stat-val'>{$stats['total']}</div>
                </div>
                <div class='stat-box'>
                    <div class='stat-title'>Approved Students</div>
                    <div class='stat-val' style='color: green;'>{$stats['approved']}</div>
                </div>
                <div class='stat-box'>
                    <div class='stat-title'>Withdrawn</div>
                    <div class='stat-val' style='color: gray;'>{$stats['withdrawn']}</div>
                </div>
                <div class='stat-box'>
                    <div class='stat-title'>Filters Applied</div>
                    <div class='stat-val' style='font-size: 11px;'>
                        Status: {$filters['application_status']}<br>
                        Type: {$filters['application_type']}<br>
                        Dept: " . ($filters['department_name'] ?? 'All') . "<br>
                        Year: " . (!empty($filters['academic_year']) ? academic_year_label($filters['academic_year']) : 'All') . "
                    </div>
                </div>
            </div>";

        // Group participants by Department → Year (each row is one person)
        $grouped = [];
        foreach ($applications as $app) {
            $dept = $app['student_department'] ?? 'Unknown Dept';
            $year = $app['student_year'] ?? 'Unknown Year';
            $grouped[$dept][$year][] = $app;
        }

        if (empty($grouped)) {
            $html .= "<div class='text-center' style='margin-top: 50px; font-size: 14px;'>No registrations found matching the selected criteria.</div>";
        }

        foreach ($grouped as $dept => $years) {
            foreach ($years as $year => $apps) {
                $html .= "
                <h4 style='text-align: left; background-color: #343a40; color: white; padding: 5px 10px; margin-top: 20px;'>
                    {$dept} — " . academic_year_label($year) . "
                </h4>
                <table>
                    <thead>
                        <tr>
                            <th style='width: 5%;'>S.No</th>
                            <th style='width: 18%;'>Reg Number</th>
                            <th style='width: 25%;'>Student Name</th>
                            <th style='width: 15%;'>Department</th>
                            <th style='width: 8%;'>Year</th>
                            <th style='width: 12%; text-align: center;'>Type / Role</th>
                            <th style='width: 10%; text-align: center;'>Status</th>
                            <th style='width: 7%; text-align: center;'>Date</th>
                        </tr>
                    </thead>
                    <tbody>";

                $sno = 1;
                foreach ($apps as $app) {
                    $isTeam   = ($app['application_type'] ?? '') === 'Team';
                    $isLeader = (bool)($app['is_team_leader'] ?? !$isTeam);

                    $date   = !empty($app['applied_at']) ? date('d-m-Y', strtotime($app['applied_at'])) : '—';
                    $teamId = !empty($app['team_id']) ? 'TEAM-' . $app['team_id'] : '';

                    $statusColor = match($app['application_status'] ?? '') {
                        'Approved'  => 'green',
                        'Pending'   => 'orange',
                        'Rejected', 'Cancelled', 'Withdrawn' => 'red',
                        default     => 'black'
                    };
                    $statusLabel = "<span style='color:{$statusColor}; font-weight:bold;'>{$app['application_status']}</span>";

                    if ($isTeam) {
                        $roleLabel = $isLeader
                            ? "<span style='color:#856404; font-weight:bold;'>&#9733; Leader</span>"
                            : "<span style='color:#555;'>&#128100; Member</span>";
                        $typeCell  = "Team<br><small style='color:#888;'>{$teamId}</small><br>{$roleLabel}";
                    } else {
                        $typeCell = 'Individual';
                    }

                    $rowBg = ($isTeam && $isLeader) ? "background-color:#fff8e1;" : "";

                    $html .= "
                        <tr style='{$rowBg}'>
                            <td>" . ($isTeam && !$isLeader ? '' : $sno++) . "</td>
                            <td>" . htmlspecialchars($app['register_number'] ?? '', ENT_QUOTES) . "</td>
                            <td>" . htmlspecialchars($app['student_name']    ?? '', ENT_QUOTES) . "</td>
                            <td>" . htmlspecialchars($app['student_department'] ?? '', ENT_QUOTES) . "</td>
                            <td class='text-center'>" . htmlspecialchars((string)($app['student_year'] ?? ''), ENT_QUOTES) . "</td>
                            <td class='text-center' style='font-size:9px;'>{$typeCell}</td>
                            <td class='text-center'>{$statusLabel}</td>
                            <td class='text-center'>{$date}</td>
                        </tr>";

                    // For team leader rows, increment sno once (leader = numbered, members = blank)
                    if ($isTeam && $isLeader) {
                        // sno already incremented above
                    }
                }

                $html .= "
                    </tbody>
                </table>";
            }
        }

        $html .= "
        </body>
        </html>";


        $options = new \Dompdf\Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', true);
        
        $dompdf = new \Dompdf\Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        
        $filename = "Registration_Report_" . preg_replace('/[^a-zA-Z0-9_-]/', '_', $event['event_code']) . ".pdf";
        
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename="' . $filename . '"');
        header('Cache-Control: private, max-age=0, must-revalidate');
        header('Pragma: public');
        
        echo $dompdf->output();
        exit;
    }

    /**
     * Generate the Attendance Report PDF using dompdf
     *
     * @param array $event
     * @param array $participants
     * @param array $summary
     * @param array $deptBreakdown
     * @param array $ficAssignments
     * @param array $user
     */
    public function generateAttendancePdf(array $event, array $participants, array $summary, array $deptBreakdown, array $ficAssignments, array $user): void
    {
        $settingModel = new \App\Models\SystemSettingModel();
        $rawLogoPath = $settingModel->getValue('COLLEGE_LOGO');
        
        $logoBase64 = '';
        if (!empty($rawLogoPath)) {
            $fullPath = __DIR__ . '/../../public/' . ltrim(str_replace(['NexusCore/', 'public/'], '', $rawLogoPath), '/');
            if (file_exists($fullPath)) {
                $type = pathinfo($fullPath, PATHINFO_EXTENSION);
                $data = file_get_contents($fullPath);
                $logoBase64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
            }
        }

        $nexusLogoPath = __DIR__ . '/../../public/assets/images/logo/nexuscore-logo.png';
        $nexusLogoBase64 = '';
        if (file_exists($nexusLogoPath)) {
            $type = pathinfo($nexusLogoPath, PATHINFO_EXTENSION);
            $data = file_get_contents($nexusLogoPath);
            $nexusLogoBase64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
        }

        $fics = implode(', ', array_column($ficAssignments, 'full_name'));
        if (empty($fics)) $fics = 'None Assigned';

        $html = "
        <html>
        <head>
            <meta charset='utf-8'>
            <style>
                body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; margin: 10px; }
                .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
                .logo { max-height: 60px; }
                .college-name { font-size: 18px; font-weight: bold; margin: 5px 0; }
                .report-title { font-size: 16px; font-weight: bold; margin: 10px 0; text-transform: uppercase; }
                .event-details { width: 100%; margin-bottom: 20px; border-collapse: collapse; }
                .event-details td { padding: 4px; vertical-align: top; }
                .summary-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                .summary-table th, .summary-table td { border: 1px solid #ddd; padding: 6px; text-align: center; }
                .summary-table th { background-color: #f5f5f5; font-weight: bold; }
                .main-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                .main-table th, .main-table td { border: 1px solid #000; padding: 6px; text-align: left; }
                .main-table th { background-color: #f0f0f0; font-weight: bold; text-align: center; }
                .text-center { text-align: center !important; }
                .footer { position: fixed; bottom: -20px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ddd; padding-top: 5px; font-size: 9px; color: #555; }
                .footer-table { width: 100%; }
                .footer-table td { padding: 0; }
                .page-number:after { content: counter(page); }
            </style>
        </head>
        <body>
            <div class='footer'>
                <table class='footer-table'>
                    <tr>
                        <td style='width: 33%;'>Generated on: " . date('Y-m-d H:i:s') . "</td>
                        <td style='width: 33%; text-align: center;'>Generated by: " . htmlspecialchars($user['full_name'] ?? '') . "</td>
                        <td style='width: 33%; text-align: right;'>Page <span class='page-number'></span></td>
                    </tr>
                </table>
            </div>

            <div class='header'>
                <table style='width: 100%;'>
                    <tr>
                        <td style='width: 15%; text-align: left;'>
                            " . ($logoBase64 ? "<img src='{$logoBase64}' class='logo'>" : "") . "
                        </td>
                        <td style='width: 70%; text-align: center;'>
                            <div class='college-name'>" . htmlspecialchars($settingModel->getValue('COLLEGE_NAME') ?: 'College Name') . "</div>
                            <div class='report-title'>Attendance Report</div>
                        </td>
                        <td style='width: 15%; text-align: right;'>
                            " . ($nexusLogoBase64 ? "<img src='{$nexusLogoBase64}' class='logo' style='max-height: 70px;'>" : "") . "
                        </td>
                    </tr>
                </table>
            </div>

            <table class='event-details'>
                <tr>
                    <td style='width: 15%; font-weight: bold;'>Event:</td>
                    <td style='width: 35%;'>" . htmlspecialchars($event['event_name'] ?? '') . " (" . htmlspecialchars($event['event_code'] ?? '') . ")</td>
                    <td style='width: 15%; font-weight: bold;'>Symposium:</td>
                    <td style='width: 35%;'>" . htmlspecialchars($event['symposium_title'] ?? '') . "</td>
                </tr>
                <tr>
                    <td style='font-weight: bold;'>Date:</td>
                    <td>" . (!empty($event['event_date']) ? \App\Helpers\DateHelper::date($event['event_date']) : 'N/A') . "</td>
                    <td style='font-weight: bold;'>Faculty In-Charge:</td>
                    <td>" . htmlspecialchars($fics) . "</td>
                </tr>
            </table>

            <table class='summary-table'>
                <tr>
                    <th>Total Registered</th>
                    <th>Present</th>
                    <th>Absent</th>
                    <th>Late</th>
                    <th>Unmarked</th>
                    <th>Attendance %</th>
                </tr>
                <tr>
                    <td>" . (int)($summary['total_registered'] ?? 0) . "</td>
                    <td style='color: green; font-weight: bold;'>" . (int)($summary['present'] ?? 0) . "</td>
                    <td style='color: red; font-weight: bold;'>" . (int)($summary['absent'] ?? 0) . "</td>
                    <td style='color: orange; font-weight: bold;'>" . (int)($summary['late'] ?? 0) . "</td>
                    <td>" . (int)($summary['unmarked'] ?? 0) . "</td>
                    <td><b>" . (float)($summary['attendance_pct'] ?? 0) . "%</b></td>
                </tr>
            </table>

            <table class='main-table'>
                <thead>
                    <tr>
                        <th style='width: 5%;'>S.No</th>
                        <th style='width: 15%;'>Reg. Number</th>
                        <th style='width: 35%; text-align: left;'>Participant Name</th>
                        <th style='width: 30%; text-align: left;'>Department</th>
                        <th style='width: 15%;'>Status</th>
                    </tr>
                </thead>
                <tbody>";

        $sno = 1;
        foreach ($participants as $p) {
            $status = $p['attendance_status'] ?? 'Unmarked';
            $statusColor = match($status) {
                'Present' => 'green',
                'Absent'  => 'red',
                'Late'    => 'orange',
                default   => '#666'
            };

            $html .= "
                    <tr>
                        <td class='text-center'>{$sno}</td>
                        <td class='text-center'>" . htmlspecialchars($p['register_number'] ?? '') . "</td>
                        <td>" . htmlspecialchars($p['student_name'] ?? '') . "</td>
                        <td>" . htmlspecialchars($p['department_name'] ?? '') . "</td>
                        <td class='text-center' style='color: {$statusColor}; font-weight: bold;'>{$status}</td>
                    </tr>";
            $sno++;
        }

        if (empty($participants)) {
            $html .= "<tr><td colspan='5' class='text-center'>No participants found for this event.</td></tr>";
        }

        $html .= "
                </tbody>
            </table>
        </body>
        </html>";

        $options = new \Dompdf\Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', true);
        
        $dompdf = new \Dompdf\Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        
        $filename = "Attendance_Report_" . preg_replace('/[^a-zA-Z0-9_-]/', '_', $event['event_code']) . ".pdf";
        
        header('Content-Type: application/pdf');
        header('Content-Disposition: inline; filename="' . $filename . '"');
        header('Cache-Control: private, max-age=0, must-revalidate');
        header('Pragma: public');
        
        echo $dompdf->output();
        exit;
    }
    /**
     * -------------------------------------------------------------------------
     * Generate the Judge Mark Sheet PDF for a specific judge and finalized session.
     *
     * @param array $event
     * @param array $students
     * @param array $judgeAssignment
     * @param array $collegeDetails
     * @return void
     * -------------------------------------------------------------------------
     */
    public function generateJudgeMarkSheetPdf(array $event, array $students, array $judgeAssignment, array $collegeDetails): void
    {
        $settingModel = new \App\Models\SystemSettingModel();
        
        $collegeName = $collegeDetails['college_name'] ?? 'COLLEGE NAME';
        
        $rawLogoPath = $settingModel->getValue('COLLEGE_LOGO');
        
        $logoBase64 = '';
        if (!empty($rawLogoPath)) {
            $fullPath = __DIR__ . '/../../public/' . ltrim(str_replace(['NexusCore/', 'public/'], '', $rawLogoPath), '/');
            if (file_exists($fullPath)) {
                $type = pathinfo($fullPath, PATHINFO_EXTENSION);
                $data = file_get_contents($fullPath);
                $logoBase64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
            }
        }

        $nexusLogoPath = __DIR__ . '/../../public/assets/images/logo/nexuscore-logo.png';
        $nexusLogoBase64 = '';
        if (file_exists($nexusLogoPath)) {
            $type = pathinfo($nexusLogoPath, PATHINFO_EXTENSION);
            $data = file_get_contents($nexusLogoPath);
            $nexusLogoBase64 = 'data:image/' . $type . ';base64,' . base64_encode($data);
        }

        // Meta information
        $eventName = htmlspecialchars($event['event_name'] ?? '');
        $eventCode = htmlspecialchars($event['event_code'] ?? '');
        $symposium = htmlspecialchars($event['symposium_title'] ?? 'Nexus 2026');
        $eventDate = !empty($event['event_date']) ? \App\Helpers\DateHelper::date($event['event_date']) : 'TBA';
        $maxMark   = htmlspecialchars((string)($event['maximum_score'] ?? '100'));
        $judgeName = htmlspecialchars($judgeAssignment['full_name'] ?? '');
        $judgeDept = htmlspecialchars($judgeAssignment['department_name'] ?? '');

        // Prepare CSS
        $css = "
            <style>
                body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; margin: 10px; }
                .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
                .logo { max-height: 60px; }
                .college-name { font-size: 18px; font-weight: bold; margin: 5px 0; }
                .report-title { font-size: 16px; font-weight: bold; margin: 10px 0; text-transform: uppercase; }
                .event-details { width: 100%; margin-bottom: 20px; border-collapse: collapse; }
                .event-details td { padding: 4px; vertical-align: top; }
                .main-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
                .main-table th, .main-table td { border: 1px solid #000; padding: 8px 6px; text-align: left; }
                .main-table th { background-color: #f0f0f0; font-weight: bold; text-align: center; }
                .text-center { text-align: center !important; }
                .signature-section { margin-top: 50px; width: 100%; page-break-inside: avoid; border: none; }
                .signature-section td { border: none; vertical-align: bottom; }
                .footer { position: fixed; bottom: -20px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ddd; padding-top: 5px; font-size: 9px; color: #555; }
                .footer-table { width: 100%; }
                .footer-table td { padding: 0; border: none; }
                .page-number:after { content: counter(page); }
            </style>
        ";

        $html = "
        <html>
        <head>
            <meta charset='UTF-8'>
            <title>Judge Mark Sheet</title>
            $css
        </head>
        <body>
            <div class='footer'>
                <table class='footer-table'>
                    <tr>
                        <td style='width: 33%;'>Generated on: " . date('Y-m-d H:i:s') . "</td>
                        <td style='width: 33%; text-align: center;'>NexusCore EMS | Official Judge Mark Sheet</td>
                        <td style='width: 33%; text-align: right;'>Page <span class='page-number'></span></td>
                    </tr>
                </table>
            </div>

            <div class='header'>
                <table style='width: 100%; border: none;'>
                    <tr>
                        <td style='width: 15%; text-align: left; border: none;'>
                            " . ($logoBase64 ? "<img src='{$logoBase64}' class='logo'>" : "") . "
                        </td>
                        <td style='width: 70%; text-align: center; border: none;'>
                            <div class='college-name'>" . htmlspecialchars($settingModel->getValue('COLLEGE_NAME') ?: $collegeName) . "</div>
                            <div class='report-title'>JUDGE MARK SHEET</div>
                        </td>
                        <td style='width: 15%; text-align: right; border: none;'>
                            " . ($nexusLogoBase64 ? "<img src='{$nexusLogoBase64}' class='logo' style='max-height: 70px;'>" : "") . "
                        </td>
                    </tr>
                </table>
            </div>

            <table class='event-details'>
                <tr>
                    <td style='width: 15%; font-weight: bold;'>Event:</td>
                    <td style='width: 35%;'>{$eventName} ({$eventCode})</td>
                    <td style='width: 15%; font-weight: bold;'>Symposium:</td>
                    <td style='width: 35%;'>{$symposium}</td>
                </tr>
                <tr>
                    <td style='font-weight: bold;'>Date:</td>
                    <td>{$eventDate}</td>
                    <td style='font-weight: bold;'>Max Mark:</td>
                    <td style='font-size: 14px; font-weight: bold;'>{$maxMark}</td>
                </tr>
                <tr>
                    <td style='font-weight: bold;'>Judge Name:</td>
                    <td>{$judgeName}</td>
                    <td style='font-weight: bold;'>Department:</td>
                    <td>{$judgeDept}</td>
                </tr>
            </table>

            <table class='main-table'>
                <thead>
                    <tr>
                        <th style='width: 6%;'>S.No</th>
                        <th style='width: 15%;'>Reg. Number</th>
                        <th style='width: 30%; text-align: left;'>Student Name</th>
                        <th style='width: 10%;'>Year</th>
                        <th style='width: 24%; text-align: left;'>Department</th>
                        <th style='width: 15%;'>Marks</th>
                    </tr>
                </thead>
                </tbody>
        ";

        // Group students by application_id
        $grouped = [];
        foreach ($students as $student) {
            $appId = $student['application_id'] ?? 'unknown';
            $grouped[$appId][] = $student;
        }

        $sno = 1;
        foreach ($grouped as $appId => $members) {
            $first = $members[0];
            $isTeam = ($first['application_type'] ?? '') === 'Team';
            
            if ($isTeam) {
                $teamId = htmlspecialchars((string)($first['team_id'] ?? ''));
                $appNo  = htmlspecialchars((string)($first['application_no'] ?? ''));
                $memberCount = count($members);
                $rowSpan = $memberCount + 1;
                
                // Team Header Row with rowspan for Marks
                $html .= "
                    <tr>
                        <td class='text-center' rowspan='{$rowSpan}'>{$sno}</td>
                        <td colspan='4' style='background-color: #f8f9fa; font-weight: bold;'>
                            TEAM: {$teamId} &nbsp;&nbsp;&nbsp; <span style='font-weight: normal; color: #555;'>(App No: {$appNo})</span>
                        </td>
                        <td rowspan='{$rowSpan}'></td>
                    </tr>
                ";
                
                // Member Rows (S.No and Marks columns are merged via rowspan above)
                foreach ($members as $m) {
                    $regNo = htmlspecialchars($m['register_number'] ?? '');
                    $sName = htmlspecialchars($m['student_name'] ?? '');
                    
                    $yrRaw = (string)($m['student_year'] ?? '');
                    $yrFmt = $yrRaw;
                    if ($yrRaw === '1') $yrFmt = 'I Year';
                    elseif ($yrRaw === '2') $yrFmt = 'II Year';
                    elseif ($yrRaw === '3') $yrFmt = 'III Year';
                    elseif ($yrRaw === '4') $yrFmt = 'IV Year';
                    
                    $sDept = htmlspecialchars($m['department_name'] ?? '');
                    
                    $html .= "
                        <tr>
                            <td class='text-center'>{$regNo}</td>
                            <td>{$sName}</td>
                            <td class='text-center'>{$yrFmt}</td>
                            <td>{$sDept}</td>
                        </tr>
                    ";
                }
            } else {
                // Individual Application Row
                $m = $first;
                $regNo = htmlspecialchars($m['register_number'] ?? '');
                $sName = htmlspecialchars($m['student_name'] ?? '');
                
                $yrRaw = (string)($m['student_year'] ?? '');
                $yrFmt = $yrRaw;
                if ($yrRaw === '1') $yrFmt = 'I Year';
                elseif ($yrRaw === '2') $yrFmt = 'II Year';
                elseif ($yrRaw === '3') $yrFmt = 'III Year';
                elseif ($yrRaw === '4') $yrFmt = 'IV Year';
                
                $sDept = htmlspecialchars($m['department_name'] ?? '');
                
                $html .= "
                    <tr>
                        <td class='text-center'>{$sno}</td>
                        <td class='text-center'>{$regNo}</td>
                        <td>{$sName}</td>
                        <td class='text-center'>{$yrFmt}</td>
                        <td>{$sDept}</td>
                        <td></td>
                    </tr>
                ";
            }
            $sno++;
        }

        if (empty($students)) {
            $html .= "<tr><td colspan='6' class='text-center'>No eligible students found for this event.</td></tr>";
        }

        $html .= "
                </tbody>
            </table>

            <table class='signature-section' style='border: none;'>
                <tr>
                    <td style='width: 60%; border: none;'>
                        Date: ________________________
                    </td>
                    <td style='width: 40%; text-align: center; border: none;'>
                        _________________________________<br/><br/>
                        <b>Judge Signature</b><br/>
                        {$judgeName}<br/>
                        <span style='font-size: 10px; color: #555;'>{$judgeDept}</span>
                    </td>
                </tr>
            </table>
        </body>
        </html>
        ";

        $options = new \Dompdf\Options();
        $options->set('isHtml5ParserEnabled', true);
        $options->set('isRemoteEnabled', true);
        
        $dompdf = new \Dompdf\Dompdf($options);
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'portrait');
        $dompdf->render();
        
        $filename = "Judge_Marksheet_" . preg_replace('/[^a-zA-Z0-9_-]/', '_', $eventName) . "_" . preg_replace('/[^a-zA-Z0-9_-]/', '_', $judgeName) . ".pdf";
        
        header('Content-Type: application/pdf');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Cache-Control: private, max-age=0, must-revalidate');
        header('Pragma: public');
        
        echo $dompdf->output();
        exit;
    }
}
