<?php

declare(strict_types=1);

/**
 * -------------------------------------------------------------------------
 * NexusCore
 * -------------------------------------------------------------------------
 * File        : UserValidator.php
 * Location    : app/Validators/
 * Description : Validates user input before it reaches the
 *               service and model layers.
 *
 * Responsibilities
 * ----------------
 * • Validate employee ID
 * • Validate full name
 * • Validate email
 * • Validate phone number
 * • Validate department
 * • Validate role
 * • Validate password
 * • Validate account status
 *
 * NOTE
 * ----
 * This class performs only input validation.
 * It does NOT communicate with the database.
 * Business rules belong in UserService.
 *
 * Project     : NexusCore
 * -------------------------------------------------------------------------
 */

namespace App\Validators;

use App\Helpers\RoleHelper;

final class UserValidator
{
    /**
     * ---------------------------------------------------------------------
     * Validate user data.
     *
     * @param array $data
     *
     * @return array<string, string>
     * ---------------------------------------------------------------------
     */
    public function validate(array $data): array
    {
        $errors = [];

        /*
        |--------------------------------------------------------------------------
        | Employee ID
        |--------------------------------------------------------------------------
        |
        | Employee IDs are now AUTO-GENERATED by EmployeeIdService.
        | Manual input validation is intentionally skipped here.
        | The controller passes the server-generated ID into the data array.
        | Uniqueness is enforced at the database level (UNIQUE KEY uq_employee_id).
        |--------------------------------------------------------------------------
        */

        $employeeId = trim($data['employee_id'] ?? '');

        if ($employeeId === '') {

            // Only flag as missing if it's a create (no user_id).
            // On update, employee_id is locked and not re-submitted.
            if (empty($data['user_id'])) {
                $errors['employee_id'] = 'Employee ID is required. Please select a role first.';
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Full Name
        |--------------------------------------------------------------------------
        */

        $fullName = trim($data['full_name'] ?? '');

        if ($fullName === '') {

            $errors['full_name'] =
                'Full name is required.';
        }
        elseif (mb_strlen($fullName) > 120) {

            $errors['full_name'] =
                'Full name cannot exceed 120 characters.';
        }

        /*
        |--------------------------------------------------------------------------
        | Email Address
        |--------------------------------------------------------------------------
        */

        $email = strtolower(
            trim($data['email'] ?? '')
        );

        if ($email === '') {

            $errors['email'] =
                'Email address is required.';
        } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {

            $errors['email'] =
                'Please enter a valid email address.';
        }

        /*
        |--------------------------------------------------------------------------
        | Phone Number
        |--------------------------------------------------------------------------
        */

        $phone = trim($data['phone'] ?? '');

        if ($phone !== '') {

            if (!preg_match('/^[0-9]{10,15}$/', $phone)) {

                $errors['phone'] =
                    'Phone number must contain 10 to 15 digits.';
            }
        }

        /*
        |--------------------------------------------------------------------------
        | User Role
        |--------------------------------------------------------------------------
        */

        $role = trim($data['role'] ?? '');

        if (!RoleHelper::isValidRole($role)) {

            $errors['role'] =
                'Please select a valid user role.';
        }

        /*
        |--------------------------------------------------------------------------
        | Department
        |--------------------------------------------------------------------------
        |
        | Department is mandatory for: HOD, Staff, Staff Coordinator, Student Coordinator.
        |
        | Staff Coordinator and Student Coordinator are restricted to PG departments
        | (PGCS, PGCA) — enforced via RoleHelper::getAllowedDeptCodes().
        | The submitted dept_code is checked against the allowed list.
        |--------------------------------------------------------------------------
        */

        $departmentId   = trim((string) ($data['department_id'] ?? ''));
        $departmentCode = strtoupper(trim((string) ($data['department_code'] ?? '')));

        if (RoleHelper::requiresDepartment($role) && $departmentId === '') {

            $errors['department_id'] = 'Please select a department.';
        }

        $allowedCodes = RoleHelper::getAllowedDeptCodes($role);

        if (
            $allowedCodes !== null &&
            $departmentCode !== '' &&
            !in_array($departmentCode, $allowedCodes, true)
        ) {
            $errors['department_id'] =
                'This role must belong to a PG Department (PG CS or PG CA).';
        }

        /*
        |--------------------------------------------------------------------------
        | Password
        |--------------------------------------------------------------------------
        |
        | Password validation is required only while
        | creating a new user.
        |
        */

        if (empty($data['user_id'])) {

            $password = $data['password'] ?? '';

            $confirmPassword =
                $data['confirm_password'] ?? '';

            if ($password === '') {

                $errors['password'] =
                    'Password is required.';
            }
            elseif (strlen($password) < 8) {

                $errors['password'] =
                    'Password must contain at least 8 characters.';
            }

            if ($confirmPassword === '') {

                $errors['confirm_password'] =
                    'Please confirm the password.';
            }
            elseif ($password !== $confirmPassword) {

                $errors['confirm_password'] =
                    'Passwords do not match.';
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Account Status
        |--------------------------------------------------------------------------
        */

        $accountStatus = trim(
            $data['account_status'] ?? ''
        );

        $allowedStatus = [

            'Active',

            'Inactive',

            'Blocked'

        ];

        if (!in_array($accountStatus, $allowedStatus, true)) {

            $errors['account_status'] =
                'Please select a valid account status.';
        }

        return $errors;
    }

    /**
     * ---------------------------------------------------------------------
     * Validate uploaded files.
     *
     * @param array $files
     *
     * @return array<string, string>
     * ---------------------------------------------------------------------
     */
    public function validateFiles(array $files): array
    {
        $errors = [];

        /*
        |--------------------------------------------------------------------------
        | Maximum Upload Size (2 MB)
        |--------------------------------------------------------------------------
        */

        $maxFileSize = 2 * 1024 * 1024;

        /*
        |--------------------------------------------------------------------------
        | Profile Photo
        |--------------------------------------------------------------------------
        */

        if (
            isset($files['profile_photo']) &&
            $files['profile_photo']['error'] !== UPLOAD_ERR_NO_FILE
        ) {

            $profileError = $this->validateUploadedFile(
                $files['profile_photo'],
                [
                    'jpg',

                    'jpeg',

                    'png',

                    'webp'

                ],
                $maxFileSize,
                'Profile photo'
            );

            if ($profileError !== null) {

                $errors['profile_photo'] = $profileError;
            }
        }

        /*
        |--------------------------------------------------------------------------
        | Signature
        |--------------------------------------------------------------------------
        */

        if (
            isset($files['signature_path']) &&
            $files['signature_path']['error'] !== UPLOAD_ERR_NO_FILE
        ) {

            $signatureError = $this->validateUploadedFile(
                $files['signature_path'],
                [
                    'jpg',

                    'jpeg',

                    'png'

                ],
                $maxFileSize,
                'Signature'
            );

            if ($signatureError !== null) {

                $errors['signature_path'] = $signatureError;
            }
        }

        return $errors;
    }

    /**
     * ---------------------------------------------------------------------
     * Validate a single uploaded file.
     *
     * @param array  $file
     * @param array  $allowedExtensions
     * @param int    $maxFileSize
     * @param string $label
     *
     * @return string|null
     * ---------------------------------------------------------------------
     */
    private function validateUploadedFile(
        array $file,
        array $allowedExtensions,
        int $maxFileSize,
        string $label
    ): ?string {

        if ($file['error'] === UPLOAD_ERR_INI_SIZE
            || $file['error'] === UPLOAD_ERR_FORM_SIZE
        ) {

            return $label . ' exceeds the maximum allowed file size of 2 MB.';
        }

        if ($file['error'] !== UPLOAD_ERR_OK) {

            return $label . ' upload failed. Please try again.';
        }

        $extension = strtolower(
            pathinfo(
                $file['name'],
                PATHINFO_EXTENSION
            )
        );

        if (!in_array($extension, $allowedExtensions, true)) {

            return $label . ' must be a '
                . implode(', ', $allowedExtensions)
                . ' file.';
        }

        if ($file['size'] > $maxFileSize) {

            return $label . ' exceeds the maximum allowed file size of 2 MB.';
        }

        if (@getimagesize($file['tmp_name']) === false) {

            return $label . ' must be a valid image file.';
        }

        return null;
    }
}